var searchData=
[
  ['majorpeaks_0',['MajorPeaks',['../class_major_peaks.html',1,'MajorPeaks'],['../class_major_peaks.html#a9bcd8fc64d8b8edfd1219a91ddf6e00b',1,'MajorPeaks::MajorPeaks()'],['../class_major_peaks.html#a0bd8348902b47cafc5712b5ebd17abdc',1,'MajorPeaks::MajorPeaks(int n)'],['../index.html#autotoc_md39',1,'MajorPeaks']]],
  ['majorpeaks_2eh_1',['MajorPeaks.h',['../_major_peaks_8h.html',1,'']]],
  ['maxamplitude_2',['MaxAmplitude',['../class_max_amplitude.html',1,'MaxAmplitude'],['../index.html#autotoc_md10',1,'MaxAmplitude']]],
  ['maxamplitude_2eh_3',['MaxAmplitude.h',['../_max_amplitude_8h.html',1,'']]],
  ['meanamplitude_4',['MeanAmplitude',['../class_mean_amplitude.html',1,'MeanAmplitude'],['../class_mean_amplitude.html#ab9ed79dcf26d5120f0526449bf3b122a',1,'MeanAmplitude::MeanAmplitude()'],['../index.html#autotoc_md18',1,'MeanAmplitude']]],
  ['meanamplitude_2eh_5',['MeanAmplitude.h',['../_mean_amplitude_8h.html',1,'']]],
  ['member_20functions_6',['Member Functions',['../index.html#autotoc_md51',1,'AnalysisModule Member Functions'],['../index.html#autotoc_md57',1,'ModuleInterface Member Functions']]],
  ['module_7',['Module',['../index.html#autotoc_md60',1,'Creating a Composite Module'],['../index.html#autotoc_md59',1,'Creating an Atonic Module']]],
  ['modulegroup_8',['ModuleGroup',['../class_module_group.html',1,'ModuleGroup'],['../class_module_group.html#a2db4a6dbe84ac5f62a181ba3b9833b57',1,'ModuleGroup::ModuleGroup(Spectrogram *spectrogram)'],['../class_module_group.html#afe5fe3303bef12ccff2cb83b26acfd49',1,'ModuleGroup::ModuleGroup(Spectrogram *spectrogram, int lowerFreq, int upperFreq)']]],
  ['modulegroup_2ecpp_9',['ModuleGroup.cpp',['../_module_group_8cpp.html',1,'']]],
  ['modulegroup_2eh_10',['ModuleGroup.h',['../_module_group_8h.html',1,'']]],
  ['moduleinterface_11',['ModuleInterface',['../class_module_interface.html',1,'']]],
  ['moduleinterface_20class_12',['ModuleInterface Class',['../index.html#autotoc_md55',1,'']]],
  ['moduleinterface_20data_13',['ModuleInterface Data',['../index.html#autotoc_md56',1,'']]],
  ['moduleinterface_20member_20functions_14',['ModuleInterface Member Functions',['../index.html#autotoc_md57',1,'']]],
  ['moduleinterface_3c_20bool_20_3e_15',['ModuleInterface&lt; bool &gt;',['../class_module_interface.html',1,'']]],
  ['moduleinterface_3c_20char_20_3e_16',['ModuleInterface&lt; char &gt;',['../class_module_interface.html',1,'']]],
  ['moduleinterface_3c_20float_20_2a_20_3e_17',['ModuleInterface&lt; float * &gt;',['../class_module_interface.html',1,'']]],
  ['moduleinterface_3c_20float_20_2a_2a_20_3e_18',['ModuleInterface&lt; float ** &gt;',['../class_module_interface.html',1,'']]],
  ['moduleinterface_3c_20float_20_3e_19',['ModuleInterface&lt; float &gt;',['../class_module_interface.html',1,'']]],
  ['moduleinterface_3c_20int_20_2a_20_3e_20',['ModuleInterface&lt; int * &gt;',['../class_module_interface.html',1,'']]],
  ['moduleinterface_3c_20int_20_3e_21',['ModuleInterface&lt; int &gt;',['../class_module_interface.html',1,'']]],
  ['modules_22',['Modules',['../index.html#autotoc_md58',1,'Creating Modules'],['../index.html#autotoc_md9',1,'Provided Modules']]],
  ['modules_23',['modules/*',['../index.html#autotoc_md63',1,'']]],
  ['mp_5famp_24',['MP_AMP',['../_major_peaks_8h.html#aa57f498e257f0878e75a293f9257f353',1,'MajorPeaks.h']]],
  ['mp_5ffreq_25',['MP_FREQ',['../_major_peaks_8h.html#a4c26e14384ba39fb5ee70097c6b06826',1,'MajorPeaks.h']]]
];
